language: python
python:
    - "2.7"

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: false
cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=bookscanner_control/bookscanner_control.ino

install:
    - pip install -U platformio
    - platformio update
    # https://platformio.org/lib/show/874/Stepper
    - platformio lib -g install 874

script:
    # https://store.arduino.cc/arduino-uno-rev3
    - platformio ci --lib="." --board=uno
